'use client';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect } from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@app/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const meta: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    // Cek apakah user sudah login
    const accessToken = localStorage.getItem('accessToken');
    
    // Jika tidak ada token dan bukan di halaman login, redirect ke login
    if (!accessToken && pathname !== '/login') {
      router.push('/login');
    }
    
    // Jika sudah login dan mencoba akses halaman login, redirect ke dashboard
    if (accessToken && pathname === '/login') {
      router.push('/dashboard');
    }
  }, [pathname, router]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
